name: dense_fusion
channels:
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - blas=1.0
  - bzip2=1.0.8
  - ca-certificates=2022.4.26
  - cairo=1.16.0
  - certifi=2021.5.30
  - ffmpeg=4.0
  - fontconfig=2.13.1
  - freeglut=3.0.0
  - freetype=2.11.0
  - glib=2.69.1
  - graphite2=1.3.14
  - harfbuzz=1.8.8
  - hdf5=1.10.2
  - icu=58.2
  - intel-openmp=2022.0.1
  - jasper=2.0.14
  - jpeg=9e
  - ld_impl_linux-64=2.38
  - libffi=3.3
  - libgcc-ng=11.2.0
  - libgfortran-ng=7.5.0
  - libgfortran4=7.5.0
  - libglu=9.0.0
  - libgomp=11.2.0
  - libopencv=3.4.2
  - libopus=1.3.1
  - libpng=1.6.37
  - libstdcxx-ng=11.2.0
  - libtiff=4.2.0
  - libuuid=1.0.3
  - libvpx=1.7.0
  - libwebp-base=1.2.2
  - libxcb=1.15
  - libxml2=2.9.14
  - lz4-c=1.9.3
  - mkl=2020.2
  - mkl-service=2.3.0
  - mkl_fft=1.3.0
  - mkl_random=1.1.1
  - ncurses=6.3
  - numpy-base=1.19.2
  - opencv=3.4.2
  - openssl=1.1.1o
  - pcre=8.45
  - pip=21.2.2
  - pixman=0.40.0
  - py-opencv=3.4.2
  - python=3.6.13
  - python_abi=3.6
  - readline=8.1.2
  - setuptools=49.6.0
  - six=1.16.0
  - sqlite=3.38.5
  - tk=8.6.12
  - wheel=0.37.1
  - xz=5.2.5
  - zlib=1.2.12
  - zstd=1.5.2
  - pip:
    - cycler==0.11.0
    - dataclasses==0.8
    - joblib==1.1.0
    - kiwisolver==1.3.1
    - knn-cuda==0.2
    - knn-pytorch==0.1
    - matplotlib==3.3.4
    - numpy==1.19.5
    - pillow==8.4.0
    - pyparsing==3.0.9
    - python-dateutil==2.8.2
    - pyyaml==6.0
    - scikit-learn==0.24.2
    - scipy==1.5.4
    - threadpoolctl==3.1.0
    - torch==1.2.0
    - torchvision==0.4.0
    - typing-extensions==4.1.1
